from .userController import UserController
from .documentTypeController import DocumentTypeController
from .departmentController import DepartmentController
from .documentController import DocumentController
